language: go
go:
  - 1.6
  - 1.7
  - tip

# use cheap containers
sudo: false

# Only test commits to production branch and all pull requests
branches:
  only:
  - master

matrix:
  allow_failures:
  - go: tip
